### ISSUE TITLE
Elabapy script check error 

### ISSUE THREAD

**Issue by ghost** [elabftw/elabapy#30]
Good day.
I'm trying to launch python3 script to check elabapy.
Earlier i tried to connect Brother QL-810W printer to elabFTW via elabftwrqprint (https://github.com/din14970/elabftwqrprint/issues/10), but also in vain. 
During the check the following error occures:

 Traceback (most recent call last):
  File "elabapy.py", line 3, in <module>
    import elabapy
  File "/root/.local/bin/elabapy.py", line 6, in <module>
    manager = elabapy.Manager(endpoint="https://tcbelab.com/api/v1/", token="--snip--", verify=True)
AttributeError: partially initialized module 'elabapy' has no attribute 'Manager' (most likely due to a circular import)

I've checked elabFTW URL according to your requirements - it's correct.
Any ideas what is wrong here? 
ElabFTW: 4.2.1
OS: Ubuntu 20.04
Browser: Chrome 96.0.4664.45
Python: 3.8.10

**Comment by NicolasCARPi** [comment]
Hello,

First, don't post your api key on github!! You should delete the one you posted and create a new one now that it is public. Anyone with that key has access to your account.

How did you install elabapy?

**Comment by ghost** [comment]
Hello Nicolas,
Thank you for the tip, API is changed.
I've used the following commands according to information on github:

sudo apt install python3-pip
sudo pip install --user elabftwqrprint
export PATH=$PATH:$HOME/.local/bin

Next i launch "configure_elabftw" and see the following:

/root/.local/lib/python3.8/site-packages/elabftwqrprint/_global_defaults.py:79: UserWarning: Could not load eLabFTW config file: [Errno 2] No such file or directory: '/root/.elabftwqrprint/elabconfig.yaml'. If this is unintentional make sure you run the 'configure_elabftw' script.
  warnings.warn(f"Could not load eLabFTW config file: {e}. If this is unintentional make sure you run the 'configure_elabftw' script.")
/root/.local/lib/python3.8/site-packages/elabftwqrprint/_global_defaults.py:91: UserWarning: Could not load printer config file: [Errno 2] No such file or directory: '/root/.elabftwqrprint/printerconfig.yaml'. If this is unintentional make sure you run the 'configure_printer' script.
  warnings.warn(f"Could not load printer config file: {e}. If this is unintentional make sure you run the 'configure_printer' script.")
   
Next i specify information according to requirements:

What is the URL to your eLab instance? (e.g. https://elab.example.org)? ADDRESS
Enter your API access token (create one in user settings on the web interface): TOKEN
Verify the certificate when connecting? (default: yes) ([yes]/no) yes

After about 2 minutes an error occures:

Traceback (most recent call last):
  File "./configure_elabftw", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/elabftwqrprint/configure_elabftw.py", line 40, in main
    manager.get_status()
  File "/root/.local/lib/python3.8/site-packages/elabapy/Manager.py", line 77, in get_status
    return self.send_req("status/")
  File "/root/.local/lib/python3.8/site-packages/elabapy/baseapi.py", line 80, in send_req
    req = requests_method(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='tcbelab.com', port=443): Max retries exceeded with url: /api/v1/status/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe789d33a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

Any ideas?

**Comment by NicolasCARPi** [comment]
The `pip install` step must not be made with `sudo`. Also note that your issue seems to be with elabftwqrprint, which is not maintained by me, but by @din14970.

**Comment by din14970** [comment]
They first posted an issue here https://github.com/din14970/elabftwqrprint/issues/10 but it was difficult to figure out what the problem was with the given information. Therefore I suggested to try first to connect with the `elabapy.Manager`, directly putting in the relevant information. Only if that still didn't work to create an issue here.

@glenryar have you tried the python script I suggested to troubleshoot your connection?

From the trace it simply looks like the package is getting very confused about file/import paths since you are installing as root but running them as user. As @NicolasCARPi suggest, `pip install` with your regular user. If pip complains that you must be root, try `python3 -m pip install` instead. Also it may be a good idea if you installed packages as root to uninstall them again with `sudo pip uninstall`.

If you manage to connect to the elabapy with the python script I suggested, please close this issue. If you continue to have issues with my qr code printing package re-open an issue there.

**Comment by NicolasCARPi** [comment]
> If pip complains that you must be root

That shouldn't be the case with the `--user` flag. See: https://dev.to/elabftw/stop-using-sudo-pip-install-52mn

**Comment by ghost** [comment]
I've completely uninstalled elabftwqrprint (with sudo), pip, and cleared ~.local/bin folder.
After new installation the following error occures:

Requirement already satisfied: elabftwqrprint in ./.local/lib/python3.8/site-packages (0.1.0)
Requirement already satisfied: tabulate>=0.8.7 in ./.local/lib/python3.8/site-packages (from elabftwqrprint) (0.8.9)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from elabftwqrprint) (5.3.1)
Requirement already satisfied: brother-ql>=0.9.4 in ./.local/lib/python3.8/site-packages (from elabftwqrprint) (0.9.4)
Requirement already satisfied: elabapy>=0.6.1 in ./.local/lib/python3.8/site-packages (from elabftwqrprint) (0.8.2)
Requirement already satisfied: Pillow>=7.2.0 in ./.local/lib/python3.8/site-packages (from elabftwqrprint) (8.4.0)
Requirement already satisfied: qrcode>=6.1 in ./.local/lib/python3.8/site-packages (from elabftwqrprint) (7.3.1)
Requirement already satisfied: attrs in ./.local/lib/python3.8/site-packages (from brother-ql>=0.9.4->elabftwqrprint) (21.2.0)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from brother-ql>=0.9.4->elabftwqrprint) (0.18.2)
Requirement already satisfied: packbits in ./.local/lib/python3.8/site-packages (from brother-ql>=0.9.4->elabftwqrprint) (0.6)
Requirement already satisfied: pyusb in ./.local/lib/python3.8/site-packages (from brother-ql>=0.9.4->elabftwqrprint) (1.2.1)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from brother-ql>=0.9.4->elabftwqrprint) (7.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from elabapy>=0.6.1->elabftwqrprint) (2.22.0)

Probably some dependensies are still there.
How to delete elabftwqrprint completely before fresh installation?

**Comment by ghost** [comment]
@din14970, yes, i tried to run python script you suggested, but the following error occured:

  Traceback (most recent call last):
  File "elabapy.py", line 3, in <module>
    import elabapy
  File "/root/.local/bin/elabapy.py", line 6, in <module>
    manager = elabapy.Manager(endpoint="https://tcbelab.com/api/v1/", token="TOKEN", verify=True)
AttributeError: partially initialized module 'elabapy' has no attribute 'Manager' (most likely due to a circular import)

Any ideas?

**Comment by NicolasCARPi** [comment]
> uninstalled elabftwqrprint (with sudo), pip, and cleared ~.local/bin folder.

You need to provide which commands you used and what where their return.

The "Requirement already satisfied" message is not an error, it just lets you know that the packages are here already.

**Comment by ghost** [comment]
Here are the commands and output:

1. Uninstall elabapy with sudo:

~~~
    sudo pip uninstall elabapy
    Found existing installation: elabapy 0.8.2
    Uninstalling elabapy-0.8.2:
    Would remove:
    /root/.local/lib/python3.8/site-packages/elabapy-0.8.2.dist-info/*
    /root/.local/lib/python3.8/site-packages/elabapy/*
    Proceed (y/n)? y
    Successfully uninstalled elabapy-0.8.2
~~~

2. Uninstall elabftwqrprint:

~~~
    sudo pip uninstall elabftwqrprint
    WARNING: Skipping elabftwqrprint as it is not installed.
~~~

3. Check files location:

~~~
    ls .local/lib/python3.8/site-packages/
    attr                        elabftwqrprint-0.1.0.dist-info  pyusb-1.2.1.dist-info
    attrs-21.2.0.dist-info      packbits-0.6.dist-info          qrcode
    brother_ql                  packbits.py                     qrcode-7.3.1.dist-info
    brother_ql-0.9.4.dist-info  PIL                             tabulate-0.8.9.dist-info
    elabapy                     Pillow-8.4.0.dist-info          tabulate.py
    elabapy-0.8.2.dist-info     Pillow.libs                     usb
    elabftwqrprint              __pycache__
~~~

As you can see software is not deleted, which is strange.

**Comment by NicolasCARPi** [comment]
> As you can see software is not deleted, which is strange.

You have to realize that `/root/.local` and `.local` which is in fact `$HOME/.local` are not the same folders. Unless command 3 was executed as root in `/root`.

I just tried this:

~~~bash
docker run --rm -it python:3.8-slim-buster bash
pip install elabftwqrprint
python
>>> import elabapy
>>> manager = elabapy.Manager(endpoint="https://localhost", token="aa", verify=False)
~~~

And it works fine, so I'm not sure from where you get the `AttributeError` but my guess would be a botched installation of the modules and you need to start from scratch. Alternatively, because python packaging is such a mess, you have a plethora of options to install these packages in another way (pipenv, poetry, venv, conda, etc.....) ;)

**Comment by din14970** [comment]
@glenryar Try to just install without trying to delete things: `$ pip install --user elabapy` and then running the script. Also, rename your script: since you called it elabapy.py, python will try to import the file itself when you call `import elabapy` - this is why you get the circular import error. For example, name the file `script.py` then run `$ python3 script.py`. I'm pretty sure your API should be accessible, it is really just something messed up with your python installation on your local computer.

Once this works install elabftwqrprint with `$ pip install --user elabftwqrprint`. Try again to follow the rest of the explanations in the readme over on that repo.

I'm sorry you got dragged into this discussion @NicolasCARPi , the issue really doesn't seem to be related to elabapy at all.

**Comment by NicolasCARPi** [comment]
> rename your script: since you called it elabapy.py, python will try to import the file itself when you call import elabapy - this is why you get the circular import error

Nice! Didn't catch that. Indeed this is where the error is coming from! Silly python :laughing: 

![2021-11-23-212633_793x166_scrot](https://user-images.githubusercontent.com/3043706/143098435-b616a843-4ecd-4b54-9be5-a0808c7be229.png)

**Comment by NicolasCARPi** [comment]
> I'm sorry you got dragged into this discussion @NicolasCARPi , the issue really doesn't seem to be related to elabapy at all.

Yep, but it was valuable to me, because I didn't know that the name of the script was important! I thought that you needed an `__init__.py` file in there to make it a package but I guess not...
