### ISSUE TITLE
Inconsistent encoding error

### ISSUE THREAD

**Issue by althonos** [elabftw/elabapy#4]
Hi Nicolas !

While trying to use the `elabapy` library with the running `elabftw` instance of our lab, I consistently get the following issue when trying to get the items list:
```python
>>> elabapy.Manager(endpoint="https://ELAB_HOST/api/v1/", token="TOKEN")
>>> mgr.get_all_items()
['error', 'Malformed UTF-8 characters, possibly incorrectly encoded']
```

I tried reaching the URL with `urllib.request` or `PyCurl` directly, and I get the same response from the server:
```python
>>> req = urllib.request.Request('https://ELAB_HOST/api/v1/items/')
>>> req.add_header('Authorization', 'TOKEN')
>>> res = urllib.request.urlopen(req)
>>> res.read()
b'["error", "Malformed UTF-8 characters, possibly incorrectly encoded"]'
```

The strange thing is that when trying to access to the exact same server using directly `curl` in the shell, I get the expected response:
```console
$ curl -H "Authorization: TOKEN" "https://ELAB_HOST/api/v1/items/5" -k
... lots of JSON ...
```

Since the request seem to work server side, I really have no idea where this bug may be coming from. Any idea ? :smile:

**Comment by NicolasCARPi** [comment]
Hello,

elab version?
docker?

look one by one all your items to find the one that fails, what special characters are present in it?

the curl command only fetch one item, the elabapy one fetch all, hence the difference. But the error IS server side.

what happens if you replace [this line](https://github.com/elabftw/elabftw/blob/master/app/controllers/ApiController.php#L97) with:

~~~php
$Response = new JsonResponse(mb_convert_encoding($content, 'UTF-8', 'UTF-8'));
~~~
?

**Comment by althonos** [comment]
My bad, it was a server-side error. Some of the description had invalid UTF-8 characters; after editing them everything works fine. Sorry for the inconvenience.

**Comment by NicolasCARPi** [comment]
Ok cool :)
