### ISSUE TITLE
The field `uploads` is not filled when calling `get_all_items`

### ISSUE THREAD

**Issue by fbertaux** [elabftw/elabapy#6]
While calling get_item with the item id correctly retrieves the field `uploads`.

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for reporting this issue, I'll have a look.

**Comment by NicolasCARPi** [comment]
So the thing is that to avoid code duplication, the API is using the functions used by the Web interface. And when fetching several entities, the upload data is not added for performance reason (because it's not needed in show mode). Only the 'has_attachement' field is populated to show if the given item has attached files (to display the paperclip).

Now, in your code you can fetch yourself the upload data about an experiment that has 'has_attachement'.

But I understand how it can feel weird that fetching several results yields different fields than for 1 result. I'll see if I can improve that in the future, but right now it's not an `elabapy` issue, but rather an `elabftw` issue only showing through the API access.

It would help if you can explain your use case.
